"""pets

Revision ID: 44046ea54f95
Revises: 
Create Date: 2023-06-05 11:49:57.298142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44046ea54f95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.Column('pet_type', sa.String(length=100), nullable=False),
    sa.Column('pet_age', sa.Integer(), nullable=False),
    sa.Column('pet_description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
